<a href="https://colab.research.google.com/github/OleksiiMelnichuk/MachineLearning/blob/main/%D0%9C%D0%B5%D0%BB%D1%8C%D0%BD%D0%B8%D1%87%D1%83%D0%BA_%D0%BF%D1%80_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
np.__version__

'2.0.2'

1. Створіть одновимірний масив (вектор) із арифметичною послідовністю, де кожне наступне число більше попереднього на 5, починаючи з 3, та виведіть його значення.

In [2]:
matrix = [3 + 5 * i for i in range(10)]
matrix

[3, 8, 13, 18, 23, 28, 33, 38, 43, 48]

2. Створіть двовимірний масив (матрицю) розміром 3x3, заповніть його добутками кожного числа та його попереднього, починаючи з 1, та виведіть його значення.

In [ ]:
matrix2 = np.ones((3, 3), int)
num = 1
for i in range(3):
    for j in range(3):
        if num == 1:
            matrix2[i, j] = 1
        else:
            matrix2[i, j] = num * (num - 1)
        num += 1
matrix2

array([[ 1,  2,  6],
       [12, 20, 30],
       [42, 56, 72]])

3. Створіть масив розміром 3x3, заповніть його випадковими натуральними числами від 1 до 2 та знайдіть середнє арифметичне його елементів.

In [ ]:
matrix3 = np.random.randint(1, 3, size = (3, 3))
mean = np.mean(matrix3)
print(matrix3)
print("середнє арифметичне елементів масиву:")
print(mean)

[[1 2 1]
 [2 1 1]
 [2 1 1]]
середнє арифметичне елементів масиву:
1.3333333333333333


4. Створіть масив розміром 4x4, заповніть його випадковими дійсними числами в діапазоні від 0 до 1 та знайдіть кількість елементів, що більше 0.5.

In [ ]:
matrix4 = np.random.rand(4, 4)
count = np.sum(matrix4 > 0.5)
print(matrix4)
print("Кількість елементів, що більше 0.5:")
print(count)

[[0.81644034 0.85323101 0.11884288 0.62513077]
 [0.22923918 0.08150248 0.47141907 0.87288433]
 [0.69567936 0.4259013  0.94516924 0.36342277]
 [0.70990319 0.15100968 0.09617896 0.82618874]]
Кількість елементів, що більше 0.5.
8


5. Створіть два одновимірних масиви розміром 7, заповніть їх випадковими цілими числами від -15 до 15 та виконайте на них поелементні операції додавання, віднімання та множення.

In [ ]:
matrix5_1 = np.random.randint(-15, 16, size=7)
matrix5_2 = np.random.randint(-15, 16, size=7)
print("Матриця №1:")
print(matrix5_1)
print("Матриця №2:")
print(matrix5_2)
sum = matrix5_1 + matrix5_2
print("Додавання матриці №1 та матриці №2:")
print(sum)
difference1 = matrix5_1 - matrix5_2
difference2 = matrix5_2 - matrix5_1
print("Віднімання матриці №2 від матриці №1:")
print(difference1)
print("Віднімання матриці №1 від матриці №2:")
print(difference2)
product = matrix5_1 * matrix5_2
print("Добуток матриці №1 та матриці №2:")
print(product)

Матриця №1
[ 13  -1   0  11   5 -13 -10]
Матриця №2
[-15  15   7  -9  -9 -12   3]
Додавання матриці №1 та матриці №2
[ -2  14   7   2  -4 -25  -7]
Віднімання матриці №2 від матриці №1
[ 28 -16  -7  20  14  -1 -13]
Віднімання матриці №1 від матриці №2
[-28  16   7 -20 -14   1  13]
Добуток матриці №1 та матриці №2
[-195  -15    0  -99  -45  156  -30]


6. Створіть дві матриці 4x4, заповніть їх довільними цілими числами від 1 до 10 та знайдіть їх добуток.

In [ ]:
matrix6_1 = np.random.randint(1, 11, size = (4, 4))
matrix6_2 = np.random.randint(1, 11, size = (4, 4))
print("Матриця №1:")
print(matrix6_1)
print("Матриця №1:")
print(matrix6_2)
product2 = np.dot(matrix6_1, matrix6_2)
print("Добуток матриць:")
print(product2)

Матриця №1:
[[ 3  7 10  3]
 [10  9  1  5]
 [ 4  9  2  2]
 [10  5  6 10]]
Матриця №1:
[[ 3  9  8  7]
 [ 2  7  5 10]
 [ 8 10  2  2]
 [ 9  3  5  6]]
Добуток матриць:
[[130 185  94 129]
 [101 178 152 192]
 [ 64 125  91 134]
 [178 215 167 192]]


7. Створіть дві матриці розміром 4x2 та 2x5, заповніть їх випадковими цілими числами в діапазоні від 1 до 1 0 та перемножте їх між собою.

In [ ]:
matrix7_1 = np.random.randint(1, 11, size = (4, 2))
matrix7_2 = np.random.randint(1, 11, size = (2, 5))
print("Матриця №1:")
print(matrix7_1)
print("Матриця №1:")
print(matrix7_2)
product3 = np.dot(matrix7_1, matrix7_2)
print("Добуток матриць:")
print(product3)

Матриця №1:
[[ 1  8]
 [ 3  5]
 [ 9  2]
 [ 2 10]]
Матриця №1:
[[ 1  9 10  3  7]
 [10  9  1  2  7]]
Добуток матриць:
[[ 81  81  18  19  63]
 [ 53  72  35  19  56]
 [ 29  99  92  31  77]
 [102 108  30  26  84]]


8. Створіть матрицю розміром 2x2, заповніть її випадковими цілими числами в діапазоні від 1 до 12 та знайдіть її обернену матрицю.

In [ ]:
matrix8 = np.random.randint(1, 13, size = (2, 2))
print(matrix8)
inverse_matrix8 = np.linalg.inv(matrix8)
print("Обернена матриця:")
print(inverse_matrix8)

[[5 6]
 [9 3]]
Обернена матриця:
[[-0.07692308  0.15384615]
 [ 0.23076923 -0.12820513]]


9. Створіть матрицю розміром 3x3, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та транспонуйте її.

In [ ]:
matrix9 = np.random.rand(3, 3)
print(matrix9)
matrix9T = matrix9.T
print("Транспонована матриця:")
print(matrix9T)

[[0.97886353 0.81910809 0.90697433]
 [0.12868904 0.30968022 0.33791723]
 [0.75272173 0.21512121 0.49410543]]
Транспонована матриця:
[[0.97886353 0.12868904 0.75272173]
 [0.81910809 0.30968022 0.21512121]
 [0.90697433 0.33791723 0.49410543]]


10. Створіть матрицю розміром 3x4 та вектор розміром 4x1, заповніть матрицю
випадковими дійсними числами від 0 до 1, а вектор - випадковими дійсними числами від 0 до 1 і знайдіть добуток матриці на вектор.

In [ ]:
matrix10 = np.random.rand(3, 4)
vector = np.random.rand(4, 1)
print("Матриця:")
print(matrix10)
print("Вектор:")
print(vector)
product4 = np.dot(matrix10, vector)
print("Добуток матриці на вектор:")
print(product4)

Матриця:
[[0.81622204 0.87909839 0.12523998 0.25703593]
 [0.53848754 0.42972042 0.5773542  0.45819811]
 [0.62026347 0.71346084 0.18084166 0.87272364]]
Вектор:
[[0.6042314 ]
 [0.05379362]
 [0.33772932]
 [0.86797576]]
Добуток матриці на вектор:
[[0.80587504]
 [0.94118159]
 [1.2317408 ]]


11. Створіть матрицю розміром 2x3 та вектор розміром 3, заповніть матрицю випадковими дійсними числами від 0 до 1, а вектор - випадковими цілими числами в діапазоні від 1 до 10, і знайдіть добуток матриці на вектор.

In [ ]:
matrix11 = np.random.rand(2, 3)
vector2 = np.random.randint(1, 11, size = 3)
print("Матриця:")
print(matrix11)
print("Вектор:")
print(vector2)
product5 = np.dot(matrix11, vector2)
print("Добуток матриці на вектор:")
print(product5)

Матриця:
[[0.61404845 0.79688445 0.12636309]
 [0.18978586 0.04002887 0.36170588]]
Вектор:
[ 5  8 10]
Добуток матриці на вектор:
[10.70894874  4.88621903]


12. Створіть дві матриці розміром 4x4, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть різницю всіх елементів обох матриць.

In [ ]:
matrix12_1 = np.random.randint(1, 11, size = (4, 4))
matrix12_2 = np.random.randint(1, 11, size = (4, 4))
print("Матриця №1:")
print(matrix12_1)
print("Матриця №2:")
print(matrix12_2)
difference2 = matrix12_1 - matrix12_2
print("Різниця всіх елементів обох матриць:")
print(difference2)

Матриця №1:
[[ 4  6  1  5]
 [ 8  9  9  4]
 [10  8  4  8]
 [ 7  4  9  6]]
Матриця №2:
[[ 4 10  2  3]
 [ 8  5  2  9]
 [ 1  9  8  9]
 [ 4  5 10  1]]
Різниця всіх елементів обох матриць:
[[ 0 -4 -1  2]
 [ 0  4  7 -5]
 [ 9 -1 -4 -1]
 [ 3 -1 -1  5]]


13. Створіть дві матриці розміром 3x3, заповніть їх випадковими дійсними числами в діапазоні від -1 до 1 та знайдіть суму їх елементів.

In [ ]:
matrix13_1 = np.random.uniform(-1, 1, size=(3, 3))
matrix13_2 = np.random.uniform(-1, 1, size=(3, 3))
print("Матриця №1:")
print(matrix13_1)
print("Матриця №2:")
print(matrix13_2)
sum2 = matrix13_1 + matrix13_2
print("Сума елементів матриць:")
print(sum2)

Матриця №1:
[[-0.85233192 -0.26896095  0.94046437]
 [ 0.97727848  0.65498181  0.46154267]
 [ 0.06013565  0.47491653 -0.94794788]]
Матриця №2:
[[-0.8751966  -0.50696949 -0.07359812]
 [ 0.77339248 -0.24561912 -0.30954661]
 [ 0.88139322 -0.47670464 -0.08221605]]
Сума елементів матриць:
[[-1.72752852 -0.77593043  0.86686625]
 [ 1.75067096  0.40936269  0.15199606]
 [ 0.94152887 -0.00178811 -1.03016393]]


14. Створіть матрицю розміром 3x3, заповніть її випадковими дійсними числами в діапазоні від -3 до 3 та знайдіть кількість парних елементів матриці.

In [ ]:
matrix14 = np.random.uniform(-3, 3, size=(3, 3))
print("Матриця:")
print(matrix14)
int_matrix14 = matrix14.astype(int)
print("Матриця з цілими числами замість дійсних:")
print(int_matrix14)
even_count = np.sum(int_matrix14 % 2 == 0)
print("Кількість парних елементів матриці:")
print(even_count)

Матриця:
[[-2.18182635  0.72861803  1.11414001]
 [ 2.41525757  2.36479822  0.01424613]
 [-1.52936457 -2.54872163  2.94662326]]
Матриця з цілими числами замість дійсних:
[[-2  0  1]
 [ 2  2  0]
 [-1 -2  2]]
кількість парних елементів матриці:
7


15. Створіть матрицю розміром 5x5, заповніть її випадковими дійсними числами в діапазоні від -0.5 до 0.5 та знайдіть вектор-стовпчик, що містить середнє геометричне значення елементів кожного рядка матриці.

In [ ]:
from scipy.stats import gmean
matrix15 = np.random.uniform(-0.5, 0.5, size=(5, 5))
print("Матриця:")
print(matrix15)
positive = matrix15 + 0.5
print("Матриця з додаванням 0.5:")
print(positive)
g_mean = gmean(positive, axis = 1).reshape(-1, 1)
print("Середнє геометричне значення елементів кожного рядка матриці:")
print(g_mean)

Матриця:
[[ 0.46294672 -0.16168074  0.40418451  0.20602905 -0.37844355]
 [ 0.26830925 -0.35679171 -0.21519946 -0.08109    -0.39337919]
 [ 0.20091339 -0.30350747  0.20705161  0.23409566  0.35270258]
 [-0.36334273  0.41929209  0.00668885  0.12935078  0.22991968]
 [-0.24674252  0.17135516  0.14133176  0.16409163 -0.27472532]]
Матриця з додаванням 0.5:
[[0.96294672 0.33831926 0.90418451 0.70602905 0.12155645]
 [0.76830925 0.14320829 0.28480054 0.41891    0.10662081]
 [0.70091339 0.19649253 0.70705161 0.73409566 0.85270258]
 [0.13665727 0.91929209 0.50668885 0.62935078 0.72991968]
 [0.25325748 0.67135516 0.64133176 0.66409163 0.22527468]]
Середнє геометричне значення елементів кожного рядка матриці:
[[0.47924471]
 [0.26865909]
 [0.57148173]
 [0.49339994]
 [0.4390435 ]]


Висновок: під час виконання лабораторної роботи №1 з машинного навчання, був створенний в Colab новий блокнот та виконано 15 завданнь по матрицям використовуючи елементи лінійної алгебри за допомогою мови програмування Python та бібліотек Numpy та функції gmean з підмодуля бібліотеки SciPy, а саме scipy.stats, яка обчислює геометричне середнє масиву чисел. Під час виконання було створено вектори та двовимерні матриці, які було заповнено випадковими чи довільними, а також цілими або дійсними числами. З матрицями виконувалися поелементні операції, як додавання, віднімання та множення.  Я знаходив обернену матрицю, також транспонував матрицю.